// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cs2Bot.Models;

public partial class PatchNotesSetting
{
    public long GuildId { get; set; }

    public bool PatchNotesEnabled { get; set; }

    public long? ChannelId { get; set; }

    public virtual Guild Guild { get; set; }
}