// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Cs2Bot.Models;

public partial class BotDbContext : DbContext
{
    public BotDbContext(DbContextOptions<BotDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Guild> Guilds { get; set; }

    public virtual DbSet<PatchNotesSetting> PatchNotesSettings { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseMySql("Name=ConnectionStrings:Db", Microsoft.EntityFrameworkCore.ServerVersion.Parse("8.0.30-mysql"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Guild>(entity =>
        {
            entity.HasKey(e => e.GuildId).HasName("PRIMARY");

            entity.Property(e => e.GuildId).ValueGeneratedNever();
        });

        modelBuilder.Entity<PatchNotesSetting>(entity =>
        {
            entity.HasKey(e => e.GuildId).HasName("PRIMARY");

            entity.Property(e => e.GuildId).ValueGeneratedNever();

            entity.HasOne(d => d.Guild).WithOne(p => p.PatchNotesSetting)
                .HasForeignKey<PatchNotesSetting>(d => d.GuildId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PatchNotesSettings_ibfk_1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}